### ISSUE TITLE
Use pecl source

### ISSUE THREAD

**Issue by andypost** [wodby/xhprof#1]
There's official release now https://pecl.php.net/package-changelog.php?package=xhprof&release=2.1.2

**Comment by csandanov** [comment]
Hi, thank you for sharing but this repository is for xhprof viewer, not the extension. I guess you meant that we should consider replacing tideways xhprof extension with the extension you suggested in https://github.com/wodby/php

**Comment by csandanov** [comment]
Oh, I see, it's actually a fork of https://github.com/phacility/xhprof, which we've been using now. Yes, we should use the PECL version. And, additionally, consider replacing the tideways xhprof in wodby/php
